// Browser / Web Worker build of the sandbox module (server/sandbox), adapted from the browser-engine spike
// (scratch/browser-engine 0d3b7f756, browser-spike/build.mjs; see SPIKE-browser-engine.md for the reasoning).
//
//   npx tsc -p test/tsconfig.json          # repo root: compiles server + test helpers into build/ (CommonJS)
//   node sandbox-worker/tools/pack-cards.mjs
//   node sandbox-worker/build.mjs [--no-minify] [--mode=test|dev]
//
// Outputs (build/sandbox-worker/):
//   sandbox.worker.js   classic Web Worker speaking the protocol in src/worker.ts
//   sandbox.mjs         ESM library (loadCardBlob, createDispatcher); also runs in plain Node
//   cards.json          card blob (tools/pack-cards.mjs)
//
// It bundles tsc's CommonJS output, not the TS sources (esbuild miscompiles the engine's decorated classes), and
// keeps class names (the engine keys state metadata on them). No upstream file is edited: Node-only modules are
// aliased to shims, and the card registry (server/game/cards/Index.ts walks the file system) is generated.

import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const workerDir = import.meta.dirname;
const repoRoot = path.resolve(workerDir, '..');
const buildRoot = path.join(repoRoot, 'build');
const distDir = path.join(buildRoot, 'sandbox-worker'); // under build/ so lint and git ignore it

const args = Object.fromEntries(process.argv.slice(2).map((a) => {
    const [k, v] = a.replace(/^--/, '').split('=');
    return [k, v ?? true];
}));
const mode = args.mode ?? 'test';
const minify = !args['no-minify'];
const cardsDir = path.join(buildRoot, 'server/game/cards');

for (const needed of ['test/helpers/GameStateBuilder.js', 'server/sandbox/SandboxDispatcher.js']) {
    if (!fs.existsSync(path.join(buildRoot, needed))) {
        console.error(`build/${needed} is missing; run \`npx tsc -p test/tsconfig.json\` in the repo root first`);
        process.exit(1);
    }
}

// 1. Card registry: one static require per compiled card file, same rules and registration loop as cards/Index.ts
function listCardFiles(dir) {
    const files = [];
    for (const name of fs.readdirSync(dir).sort()) {
        if (name.startsWith('_')) {
            continue;
        }
        const full = path.join(dir, name);
        if (fs.lstatSync(full).isDirectory()) {
            if (!full.endsWith(`${path.sep}common`)) {
                files.push(...listCardFiles(full));
            }
        } else if (name.endsWith('.js') && dir !== cardsDir) {
            files.push(full);
        }
    }
    return files;
}

function generateCardIndex() {
    const files = listCardFiles(cardsDir);
    const list = files.map((f) => `    () => require(${JSON.stringify(f)})`).join(',\n');
    return {
        count: files.length,
        contents: `// GENERATED by sandbox-worker/build.mjs: static replacement for server/game/cards/Index.ts
const { buildAutoInitializingCardClass } = require(${JSON.stringify(path.join(buildRoot, 'server/game/core/GameObjectUtils'))});
const cardFiles = [
${list}
];
const cardsMap = new Map();
const overrideNotImplementedCardsMap = new Map();
const cardClassNames = new Set();
for (const [filepath, load] of cardFiles.entries()) {
    const fileImported = load();
    const card = 'default' in fileImported ? fileImported.default : fileImported;
    if (!card || !card.prototype) {
        throw Error(\`Failed to import card implementation #\${filepath} of the generated card index\`);
    }
    const cardId = card.prototype.getImplementationId();
    if (!cardId.id) {
        throw Error('Importing card class without id!');
    }
    if (cardsMap.has(cardId.id)) {
        throw Error(\`Importing card class with repeated id!: \${cardId.id}\`);
    }
    if (cardClassNames.has(card.name)) {
        throw Error(\`Import card class with duplicate class name: \${card.name}\`);
    }
    const wrappedCardClass = buildAutoInitializingCardClass(card);
    cardsMap.set(cardId.id, wrappedCardClass);
    cardClassNames.add(card.name);
    if (card.prototype.overrideNotImplemented) {
        overrideNotImplementedCardsMap.set(cardId.id, wrappedCardClass);
    }
}
exports.cards = cardsMap;
exports.overrideNotImplementedCards = overrideNotImplementedCardsMap;
`,
    };
}

const stripExt = (p) => p.replace(/\.(js|ts)$/, '');
const cardIndexPath = path.join(cardsDir, 'Index');
const cardIndexPlugin = {
    name: 'sandbox-card-index',
    setup(build) {
        build.onResolve({ filter: /cards[\\/]Index(\.[jt]s)?$/ }, (a) => (stripExt(path.resolve(a.resolveDir, a.path)) === cardIndexPath
            ? { path: cardIndexPath, namespace: 'sandbox-card-index' }
            : undefined));
        build.onLoad({ filter: /.*/, namespace: 'sandbox-card-index' }, () => {
            const { count, contents } = generateCardIndex();
            console.log(`  card registry: ${count} card implementation files`);
            return { contents, loader: 'js', resolveDir: cardsDir };
        });
    },
};

// 2. our src/ files import upstream modules by source path; redirect them to the compiled build/ copies so every
//    upstream module is bundled exactly once
const redirectToBuildPlugin = {
    name: 'sandbox-redirect-to-build',
    setup(build) {
        build.onResolve({ filter: /^\.\.?\// }, (a) => {
            if (!a.importer.startsWith(workerDir)) {
                return undefined;
            }
            const rel = path.relative(repoRoot, path.resolve(a.resolveDir, a.path));
            if (!(rel.startsWith(`server${path.sep}`) || rel.startsWith(`test${path.sep}`))) {
                return undefined;
            }
            for (const candidate of [`${stripExt(path.join(buildRoot, rel))}.js`, path.join(buildRoot, rel, 'index.js')]) {
                if (fs.existsSync(candidate)) {
                    return build.resolve(`./${path.basename(candidate)}`, { kind: a.kind, resolveDir: path.dirname(candidate) });
                }
            }
            throw new Error(`[sandbox-worker] no compiled file in build/ for ${rel}`);
        });
    },
};

// 3. aliases: Node built-ins / Node-only packages -> shims; disk card data -> in-memory; title lists -> runtime arrays
const shim = (name) => path.join(workerDir, 'shims', name);
const ALIASES = {
    'node:v8': shim('v8.ts'),
    v8: shim('v8.ts'),
    winston: shim('winston.ts'),
    fs: shim('node-stub.ts'),
    path: shim('node-stub.ts'),
    http: shim('node-stub.ts'),
    https: shim('node-stub.ts'),
    events: path.join(workerDir, 'node_modules/events/events.js'),
};
const aliasPlugin = {
    name: 'sandbox-aliases',
    setup(build) {
        build.onResolve({ filter: /^(node:v8|v8|winston|fs|path|http|https|events)$/ }, (a) => ({ path: ALIASES[a.path] }));
        build.onResolve({ filter: /UnitTestCardDataGetter(\.[jt]s)?$/ }, (a) => {
            const resolved = stripExt(path.resolve(a.resolveDir, a.path));
            const isUpstream = [repoRoot, buildRoot].some((r) => resolved === path.join(r, 'server/utils/cardData/UnitTestCardDataGetter'));
            return isUpstream ? { path: shim('UnitTestCardDataGetter.ts') } : undefined;
        });
        build.onResolve({ filter: /_(allNonLeaderCardTitles|playableCardTitles)\.json$/ }, (a) => ({
            path: a.path.match(/_(\w+)\.json$/)[1],
            namespace: 'sandbox-card-lists',
        }));
        build.onLoad({ filter: /.*/, namespace: 'sandbox-card-lists' }, (a) => ({
            contents: `module.exports = require(${JSON.stringify(path.join(workerDir, 'src/cardData.ts'))}).sharedCardLists.${a.path};`,
            loader: 'js',
            resolveDir: workerDir,
        }));
    },
};

const nodeEnv = mode === 'test' ? 'test' : 'development';
const common = {
    bundle: true,
    platform: 'browser',
    target: ['es2022'],
    minify,
    keepNames: true, // REQUIRED with minify (class names key engine state metadata)
    sourcemap: 'linked',
    legalComments: 'none',
    logLevel: 'warning',
    metafile: true,
    define: {
        'process.env.NODE_ENV': JSON.stringify(nodeEnv),
        'process.env.ENVIRONMENT': JSON.stringify('development'),
        __SPIKE_NODE_ENV__: JSON.stringify(nodeEnv),
        __SPIKE_ENVIRONMENT__: JSON.stringify('development'),
    },
    inject: [shim('process.ts')],
    plugins: [cardIndexPlugin, redirectToBuildPlugin, aliasPlugin],
};

fs.mkdirSync(distDir, { recursive: true });
const t0 = performance.now();
const results = await Promise.all([
    esbuild.build({ ...common, entryPoints: { sandbox: path.join(workerDir, 'src/library.ts') }, format: 'esm', outExtension: { '.js': '.mjs' }, outdir: distDir }),
    esbuild.build({ ...common, entryPoints: { 'sandbox.worker': path.join(workerDir, 'src/worker.ts') }, format: 'iife', outdir: distDir }),
]);
for (const [name, r] of [['sandbox', results[0]], ['sandbox.worker', results[1]]]) {
    fs.writeFileSync(path.join(distDir, `meta-${name}.json`), JSON.stringify(r.metafile));
}
console.log(`built in ${Math.round(performance.now() - t0)} ms (mode=${mode}, minify=${minify})`);
for (const f of ['sandbox.mjs', 'sandbox.worker.js']) {
    console.log(`  build/sandbox-worker/${f}  ${fs.statSync(path.join(distDir, f)).size} bytes`);
}
